### ISSUE TITLE
Unable to use I9/Q0 as an Input

### ISSUE THREAD

**Issue by NobodyYouKnow** [YulienPohl/GAL16V8#3]
I am unable to use I9/Q0 (pin 19) as an input port. I am receiving the following message when I try to start the simulation:

"Error calculating a step More than one output is active on a wire, causing a short circuit." /OE (pin 11) is tied low.

Suggestions on how to proceed? Thanks.

**Comment by YulienPohl** [comment]
Your are right, as far as I know Digital dosent support in-out pins and thus I havent tested it enough.
However, I have found a solution for this, I have added an additional input pin for all of them and placed them one above the other in the circuit diagram so that they can also be operated in a sub-circuit.

Could you send me your hex file so that I can test the new input/output?

**Comment by NobodyYouKnow** [comment]
Here you go. I included the relevant DIG file as well. This is inspired by the MC6801 ROM dumper project. Thanks for the quick attention.

[6801reader.zip](https://github.com/user-attachments/files/17245255/6801reader.zip)

**Comment by YulienPohl** [comment]
I have updated the circuit and have not noticed any simulation errors so far.

Please note that if a pin has been programmed as an output, no input pin may be connected unless it is a three-state with default Z value.

**Comment by NobodyYouKnow** [comment]
Can you turn on the Discussions tab? Your excellent answers have led to more questions, and I don't it is appropriate to post them as a part of this issue. If you would like me to reach out to you another way, please let me know. Thanks.
